#!/usr/bin/env python3
"""Render the CLI tree (docs/ARCHITECTURE.md) and the Claude hooks table
(README.md) FROM THE CODE, between HTML-comment markers.

    scripts/gen-cli-tree.py            # rewrite both sections in place
    scripts/gen-cli-tree.py --check    # exit 1 + unified diff when a section drifts

Why (plan-6 task 6.2, 2026-09-14): the hand-drawn tree under
`## CLI / hook surface` predated `hub`, `focus`, `bus`, `task`, `schedule`,
`refine`, `curator`, `pairs`, `taxonomy`, ... and the README hooks row was a
prose paraphrase of `hooks._claude_hook_block`. Both drifted silently every
release. Now `tests/test_docs_generated.py` compares each section with its
render, so adding a command or a hook without re-running this script fails
the suite.

Run it with the dev interpreter (`.venv-eval/bin/python scripts/gen-cli-tree.py`)
so the tree reflects the tree being committed, not the deployed build.

Markers (all four must exist; a missing pair is an error, never a silent skip):

    <!-- cli-tree:start -->    ...    <!-- cli-tree:end -->      docs/ARCHITECTURE.md
    <!-- hooks-table:start --> ...    <!-- hooks-table:end -->   README.md
"""
from __future__ import annotations

import argparse
import difflib
import sys
from pathlib import Path

import click

REPO = Path(__file__).resolve().parents[1]
TARGETS: "dict[str, Path]" = {
    "cli-tree": REPO / "docs" / "ARCHITECTURE.md",
    "hooks-table": REPO / "README.md",
}
HELP_WIDTH = 64
COMMAND_WIDTH = 110


class MarkerError(RuntimeError):
    """A doc lacks the `<!-- <name>:start/end -->` pair for a section."""


# ---- marker splice ----------------------------------------------------------

def _markers(name: str) -> "tuple[str, str]":
    return f"<!-- {name}:start -->", f"<!-- {name}:end -->"


def extract(text: str, name: str) -> str:
    """The body between the markers (exclusive), with its surrounding newlines
    stripped so a render compares byte-for-byte."""
    start, end = _markers(name)
    i, j = text.find(start), text.find(end)
    if i < 0 or j < 0 or j < i:
        raise MarkerError(f"section {name!r}: markers {start} / {end} not found")
    return text[i + len(start):j].strip("\n")


def splice(text: str, name: str, body: str) -> str:
    start, end = _markers(name)
    i, j = text.find(start), text.find(end)
    if i < 0 or j < 0 or j < i:
        raise MarkerError(f"section {name!r}: markers {start} / {end} not found")
    return text[:i + len(start)] + "\n" + body + "\n" + text[j:]


# ---- CLI tree ---------------------------------------------------------------

def _short_help(cmd: click.Command) -> str:
    first = (cmd.help or "").strip().splitlines()
    line = first[0].strip() if first else ""
    if len(line) > HELP_WIDTH:
        line = line[:HELP_WIDTH - 1].rstrip() + "…"
    return line


def _walk(grp: click.Group, prefix: str, lines: "list[str]", hidden: "list[str]") -> None:
    visible = [(n, c) for n, c in grp.commands.items() if not c.hidden]
    hidden.extend(n for n, c in grp.commands.items() if c.hidden)
    visible.sort(key=lambda nc: nc[0])
    for idx, (name, cmd) in enumerate(visible):
        last = idx == len(visible) - 1
        branch = "└── " if last else "├── "
        label = prefix + branch + name
        help_ = _short_help(cmd)
        lines.append(f"{label:<34} {help_}".rstrip() if help_ else label)
        if isinstance(cmd, click.Group):
            _walk(cmd, prefix + ("    " if last else "│   "), lines, hidden)


def render_cli_tree(root: "click.Group | None" = None, name: str = "rmx") -> str:
    if root is None:
        from refmatrix.cli import main as root  # noqa: F811 — the real tree
    lines: "list[str]" = [name]
    hidden: "list[str]" = []
    _walk(root, "", lines, hidden)
    aliases = ", ".join(f"`{h}`" for h in sorted(hidden))
    return "\n".join([
        f"Generated by `scripts/gen-cli-tree.py` from `refmatrix.cli.main` "
        f"({sum(1 for l in lines[1:] if l.strip())} visible commands); "
        f"`tests/test_docs_generated.py` fails when this drifts from the code.",
        "",
        "```",
        *lines,
        "```",
        "",
        f"{len(hidden)} hidden hyphenated aliases ({aliases}) are preserved for "
        "older scripts and hooks but are not part of the documented surface.",
    ])


# ---- hooks table ------------------------------------------------------------

def _fence(cmd: str) -> str:
    cmd = cmd.replace("|", "\\|")
    if len(cmd) > COMMAND_WIDTH:
        cmd = cmd[:COMMAND_WIDTH - 1].rstrip() + "…"
    if "`" in cmd:
        raise ValueError(f"hook command contains a backtick; table cannot fence it: {cmd!r}")
    return f"`{cmd}`"


def render_hooks_table() -> str:
    """One row per hook command, in generator order, for the DEFAULT flags
    (`enforce=False`: the cat-herder enforcement entries depend on which
    scripts a project has on disk). Paths are normalised so the render is
    machine-independent: the store is `<project>/.refmatrix`, the curated
    memory dir is `~/.claude/projects/<slug>/memory`."""
    from refmatrix.handoff import default_memory_dir
    from refmatrix.hooks import HOOK_ENV, _claude_hook_block

    fake_project = Path("/proj")
    block = _claude_hook_block(fake_project / ".refmatrix", enforce=False)
    memdir = str(default_memory_dir(fake_project))
    rows = [
        "Generated by `scripts/gen-cli-tree.py` from `hooks._claude_hook_block` "
        "(default flags, enforcement entries omitted); `rmx install-hooks --check` "
        "proves a project's installed file equals this generator's render.",
        "",
        "| Event | Matcher | Command |",
        "|---|---|---|",
    ]
    for event, entries in block["hooks"].items():
        for entry in entries:
            matcher = entry.get("matcher")
            mcell = f"`{matcher.replace('|', chr(92) + '|')}`" if matcher else "—"
            for h in entry["hooks"]:
                cmd = h["command"]
                if cmd.startswith(HOOK_ENV):
                    cmd = cmd[len(HOOK_ENV):]
                cmd = (cmd.replace(memdir, "~/.claude/projects/<slug>/memory")
                          .replace(str(fake_project) + "/", "<project>/")
                          .replace(str(Path.home()), "~"))
                cmd = " ".join(cmd.split())
                rows.append(f"| `{event}` | {mcell} | {_fence(cmd)} |")
    return "\n".join(rows)


RENDERERS = {"cli-tree": render_cli_tree, "hooks-table": render_hooks_table}


# ---- check / apply ----------------------------------------------------------

def check(targets: "dict[str, Path]" = TARGETS) -> "list[str]":
    """Unified diffs (one string per drifted section); empty = current."""
    out: "list[str]" = []
    for name, path in targets.items():
        have = extract(path.read_text(), name)
        want = RENDERERS[name]()
        if have != want:
            diff = difflib.unified_diff(
                have.splitlines(), want.splitlines(),
                fromfile=f"{path.name}:{name} (on disk)",
                tofile=f"{path.name}:{name} (rendered)", lineterm="")
            out.append("\n".join(diff))
    return out


def apply(targets: "dict[str, Path]" = TARGETS) -> "list[str]":
    """Rewrite drifted sections; returns the names that changed."""
    changed: "list[str]" = []
    for name, path in targets.items():
        text = path.read_text()
        want = RENDERERS[name]()
        if extract(text, name) != want:
            path.write_text(splice(text, name, want))
            changed.append(name)
    return changed


def main(argv: "list[str] | None" = None) -> int:
    ap = argparse.ArgumentParser(description=(__doc__ or "").splitlines()[0])
    ap.add_argument("--check", action="store_true",
                    help="diff instead of write; exit 1 on drift")
    a = ap.parse_args(argv)
    if a.check:
        diffs = check()
        for d in diffs:
            print(d)
        print("ok: docs sections match their render" if not diffs
              else f"DRIFT: {len(diffs)} section(s) differ — run scripts/gen-cli-tree.py")
        return 1 if diffs else 0
    changed = apply()
    print("rewrote: " + ", ".join(changed) if changed else "ok: nothing to rewrite")
    return 0


if __name__ == "__main__":
    sys.exit(main())
